services:
  products:
    build:
      context: ./products-service
      dockerfile: docker/php/Dockerfile
    container_name: products-service
    volumes:
      - ./products-service/app/:/var/www/html
    environment:
      - DB_HOST=host.docker.internal  # Conexión al WAMP local
      - DB_DATABASE=products
      - DB_USERNAME=root
      - DB_PASSWORD=
    networks:
      - backend
    ports:
      - "8001:80"

  inventory:
    build:
      context: ./inventory-service
      dockerfile: docker/php/Dockerfile
    container_name: inventory-service
    volumes:
      - ./inventory-service/app/:/var/www/html
    environment:
      - DB_HOST=host.docker.internal  # Conexión al WAMP local
      - DB_DATABASE=inventory
      - DB_USERNAME=root
      - DB_PASSWORD=
      - PRODUCTS_SERVICE_URL=http://products:8001
    networks:
      - backend
    ports:
      - "8002:80"

networks:
  backend:
    driver: bridge